[package]
name = "boknafisk"
version = "0.1.0"
authors = ["Declan Kelly <dkelly.home@gmail.com>"]

[[bin]]
name = "boknafisk"
path = "src/bin/main.rs"

[dependencies]
bitflags = "0.7"
lazy_static = "0.2.2"
unicode-segmentation = "1.0.1"